[[fmusim]]
arch = "aarch64"
git-tree-sha1 = "7a6902f0d8fd36a4eed33d75292f81e035997f71"
os = "macos"

    [[fmusim.download]]
    sha256 = "60ceb4276ba64f247358bdb4c6b54790d06f6fe5e5fe5c95dc07ffbb611068d2"
    url = "https://github.com/JuliaBinaryWrappers/fmusim_jll.jl/releases/download/fmusim-v0.0.39+0/fmusim.v0.0.39.aarch64-apple-darwin.tar.gz"
[[fmusim]]
arch = "aarch64"
git-tree-sha1 = "5fc3df68bb247f89842becba080acf568ef8aae0"
libc = "glibc"
os = "linux"

    [[fmusim.download]]
    sha256 = "d07b316e08bd17986e605369c032b7cc3ba5390d7715586acdc79d18b5e3f2c7"
    url = "https://github.com/JuliaBinaryWrappers/fmusim_jll.jl/releases/download/fmusim-v0.0.39+0/fmusim.v0.0.39.aarch64-linux-gnu.tar.gz"
[[fmusim]]
arch = "x86_64"
git-tree-sha1 = "18194f4dcd320a1eeac342a1a15c565fdc553a7f"
os = "macos"

    [[fmusim.download]]
    sha256 = "fc19f97163c3ec1cbc0890340f5afe2f4c41f7f86412badfb69335e5c257bae5"
    url = "https://github.com/JuliaBinaryWrappers/fmusim_jll.jl/releases/download/fmusim-v0.0.39+0/fmusim.v0.0.39.x86_64-apple-darwin.tar.gz"
[[fmusim]]
arch = "x86_64"
git-tree-sha1 = "c06533e50f53cdd254f2226dc62ab7c144c02a84"
libc = "glibc"
os = "linux"

    [[fmusim.download]]
    sha256 = "47f41a19f7338e41daf9d33d8a975f85b2a97a5810042035a026a3f5530ee1ae"
    url = "https://github.com/JuliaBinaryWrappers/fmusim_jll.jl/releases/download/fmusim-v0.0.39+0/fmusim.v0.0.39.x86_64-linux-gnu.tar.gz"
[[fmusim]]
arch = "x86_64"
git-tree-sha1 = "e45b96efd55a44d564068c01a914690b69918e01"
os = "windows"

    [[fmusim.download]]
    sha256 = "dd2ff31600722b21c3aca205e11006cb52fbd50865f3177127b710f874a9ec9f"
    url = "https://github.com/JuliaBinaryWrappers/fmusim_jll.jl/releases/download/fmusim-v0.0.39+0/fmusim.v0.0.39.x86_64-w64-mingw32.tar.gz"
