# Autogenerated wrapper script for fmusim_jll for x86_64-linux-gnu
export fmusim

using XML2_jll
using Zlib_jll
using Sundials_jll
JLLWrappers.@generate_wrapper_header("fmusim")
JLLWrappers.@declare_executable_product(fmusim)
function __init__()
    JLLWrappers.@generate_init_header(XML2_jll, Zlib_jll, Sundials_jll)
    JLLWrappers.@init_executable_product(
        fmusim,
        "bin/fmusim",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
